site :opscode

cookbook 'apt'
cookbook 'bash-completion'
cookbook 'berkshelf'
cookbook 'build-essential'
cookbook 'chef-apt-repo', git: "git@github.com:sometimesfood/chef-apt-repo.git"
cookbook 'console'
cookbook 'database'
cookbook 'locale-gen'
cookbook 'fqdn'
cookbook 'git'
cookbook 'github'
cookbook 'hub'
cookbook 'ntp'
cookbook 'openssl'
cookbook 'rsync'
cookbook 's3cmd'
cookbook 'screen'
cookbook 'silverware', github: 'infochimps-labs/ironfan-pantry', protocol: 'ssh', rel: 'cookbooks/silverware', branch: 'master'
cookbook 'snmp'
cookbook 'sshd'
cookbook 'strongswan', github: 'acommitteeoflunatics/strongswan-cookbook', protocol: 'ssh' 
cookbook 'sudo'
cookbook 'user'
cookbook 'vim'
